# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'FXSignal' do
  use_frameworks!

  # Pods for FXSignal
  
  pod 'DropDown'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'Firebase/Database'
  pod 'Firebase/Messaging'
  pod 'Alamofire'
  
end
